// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDllk16XeXU6zPj2v4jkrGi5tQLlBWivvg',
    appId: '1:1017029736370:web:0b32aa26a7ee00b33c56ab',
    messagingSenderId: '1017029736370',
    projectId: 'crisis-survivor',
    authDomain: 'crisis-survivor.firebaseapp.com',
    storageBucket: 'crisis-survivor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDhPErZZ9V5VVct0xKsQNHlGsw18Jy9HU',
    appId: '1:1017029736370:android:c5dc5e40f4f502df3c56ab',
    messagingSenderId: '1017029736370',
    projectId: 'crisis-survivor',
    storageBucket: 'crisis-survivor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQJ1641aZq6xWemrgyXTPQ5P00DmmMjgk',
    appId: '1:1017029736370:ios:cbe8346e0f11966e3c56ab',
    messagingSenderId: '1017029736370',
    projectId: 'crisis-survivor',
    storageBucket: 'crisis-survivor.firebasestorage.app',
    iosBundleId: 'com.example.crisisSurvivor',
  );
}
